apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: jenkins-csb-deploy
spec:
  #finally:
    #- name: clean-pvc-controller
    #  taskRef:
    #    kind: Task
    #    name: clean-pvc
    #  workspaces:
    #    - name: clone-directory
    #      workspace: controller-repo
    #- name: clean-pvc-jenkins-csb
    #  taskRef:
    #    kind: Task
    #    name: clean-pvc
    #  workspaces:
    #    - name: clone-directory
    #      workspace: jenkins-csb-repo
    #- name: clean-pvc-managed-secrets
    #  taskRef:
    #    kind: Task
    #    name: clean-pvc
    #  workspaces:
    #    - name: clone-directory
    #      workspace: managed-secrets-repo
  params:
    - default: test-jenkins-deploy
      description: jenkins-csb/controller branch (use main for production)
      name: controllerBranch
      type: string
    - default: "placeholder"
      description: 'Cluster name: "ocp-c1", "dev-dno", "dno"'
      name: OCP_CLUSTER
      type: string
    - description: 'For example: 2.452.4'
      name: jenkinsCsbVersion
      type: string
    - description: 'Instance name, like: ''main'', ''dev'''
      name: instance
      type: string
    - default: "placeholder"
      description: 'Team name, will be used for the project name: jenkins-csb-$TEAM'
      name: team
      type: string
    - description: Rover group for openshift permissions
      name: roverGroup
      type: string
  tasks:
    - name: clone-dno-config-repo
      params:
        - name: revision
          value: $(params.controllerBranch)
        - name: url
          value: 'git@gitlab.cee.redhat.com:ccit/deployments/dno-config.git'
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:681dc67d2aa1dbecbf65ecd229c8b181dae533bf14b07543c1aeead36aed2198
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      runAfter:
        - gather-general-facts
      workspaces:
        - name: output
          workspace: dno-config-repo
        - name: ssh-directory
          workspace: gitlab-jenkins-csb-token
      when:
        - input: $(params.OCP_CLUSTER)
          operator: in
          values:
            - dev-dno
            - dno
    - name: create-project-dno-config
      params:
        - name: BASE_IMAGE
          value: images.paas.redhat.com/it-cloud-ocp-proxy/alpine/git
        - name: GIT_USER_NAME
          value: ccit-test
        - name: GIT_USER_EMAIL
          value: ccit-test@redhat.com
        - name: GIT_SCRIPT
          value: >
            #!/bin/bash

            set -e

            git config --global --add safe.directory $(workspaces.source.path)

            cd $(workspaces.source.path)

            git switch $(params.controllerBranch)

            JENKINS_NS_VALUES_FILE="$(workspaces.source.path)/cluster.$(params.OCP_CLUSTER)/TenantNamespace/values.yaml"

            JENKINS_CMDB_ID="CIJ-001"

            PROJECT_NAME="jenkins-csb-$(params.team)" 

            apk add curl

            curl -L
            https://github.com/mikefarah/yq/releases/download/v4.44.5/yq_linux_amd64
            -o /usr/bin/yq

            chmod +x /usr/bin/yq

            yq ".applications |= (.[] | select(.cmdb_id ==
            \"${JENKINS_CMDB_ID}\").projects) += [\"${PROJECT_NAME}\"]" -i
            "${JENKINS_NS_VALUES_FILE}"

            yq eval "${JENKINS_NS_VALUES_FILE}"

            git add "$(workspaces.source.path)/cluster.$(params.OCP_CLUSTER)" 

            git commit -am "[pipeline] New Project: ${PROJECT_NAME} in
            cluster.$(params.OCP_CLUSTER)" 

            git push -u origin $(params.controllerBranch)
        - name: USER_HOME
          value: /root
        - name: VERBOSE
          value: 'true'
      runAfter:
        - clone-dno-config-repo
      taskRef:
        kind: Task
        name: git-cli
      when:
        - input: $(params.OCP_CLUSTER)
          operator: in
          values:
            - dev-dno
            - dno
      workspaces:
        - name: source
          workspace: dno-config-repo
        - name: ssh-directory
          workspace: gitlab-jenkins-csb-token
    - name: clone-controller-repo
      params:
        - name: revision
          value: $(params.controllerBranch)
        - name: url
          value: >-
            git@gitlab.cee.redhat.com:ccit/deployments/jenkins-csb/controller.git
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:681dc67d2aa1dbecbf65ecd229c8b181dae533bf14b07543c1aeead36aed2198
        - name: userHome
          value: /home/git
      runAfter:
        - gather-general-facts
      taskRef:
        kind: ClusterTask
        name: git-clone
      when:
        - input: $(tasks.gather-general-facts.results.customerArgocdExists)
          operator: in
          values:
            - 'False'
      workspaces:
        - name: output
          workspace: controller-repo
        - name: ssh-directory
          workspace: gitlab-jenkins-csb-token
    - name: jenkins-csb-create-tenant
      params:
        - name: OCP_CLUSTER
          value: $(params.OCP_CLUSTER)
        - name: jenkinsCsbVersion
          value: $(params.jenkinsCsbVersion)
        - name: instanceName
          value: $(params.instance)
        - name: teamName
          value: $(params.team)
        - name: roverGroup
          value: $(params.roverGroup)
        - name: jnlpPort
          value: $(tasks.gather-general-facts.results.availableNodePort)
      runAfter:
        - clone-controller-repo
      taskRef:
        kind: Task
        name: jenkins-csb-create-tenant
      when:
        - input: $(tasks.gather-general-facts.results.customerArgocdExists)
          operator: in
          values:
            - 'False'
      workspaces:
        - name: controller
          workspace: controller-repo
    - name: clone-jenkins-csb
      params:
        - name: url
          value: 'git@gitlab.cee.redhat.com:ccit/jenkins-csb.git'
        - name: revision
          value: main
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:681dc67d2aa1dbecbf65ecd229c8b181dae533bf14b07543c1aeead36aed2198
        - name: userHome
          value: /home/git
      runAfter:
        - gather-general-facts
      taskRef:
        kind: ClusterTask
        name: git-clone
      when:
        - input: $(tasks.gather-general-facts.results.customerRepoExists)
          operator: in
          values:
            - 'False'
      workspaces:
        - name: output
          workspace: jenkins-csb-repo
        - name: ssh-directory
          workspace: gitlab-jenkins-csb-token
    - name: push-controller-new-tenant
      params:
        - name: BASE_IMAGE
          value: images.paas.redhat.com/it-cloud-ocp-proxy/alpine/git
        - name: GIT_USER_NAME
          value: ccit-test
        - name: GIT_USER_EMAIL
          value: ccit-test@redhat.com
        - name: GIT_SCRIPT
          value: >
            ROOT_PROJECT_DIRECTORY="tenants/$(params.OCP_CLUSTER)/$(params.team)"

            git config --global --add safe.directory $(workspaces.source.path)

            cd $(workspaces.source.path)

            git switch $(params.controllerBranch)

            git add "${ROOT_PROJECT_DIRECTORY}" 

            git commit -am "[pipeline] Adding instance:
            jenkins-csb-$(params.team)/$(params.instance)" 

            git push -u origin $(params.controllerBranch)
        - name: USER_HOME
          value: /root
        - name: VERBOSE
          value: 'true'
      runAfter:
        - create-managed-repo
        - jenkins-csb-create-tenant
        - push-saml-key
        - create-openshift-project
        - create-project-dno-config
      taskRef:
        kind: Task
        name: git-cli
      when:
        - input: $(tasks.gather-general-facts.results.customerArgocdExists)
          operator: in
          values:
            - 'False'
      workspaces:
        - name: source
          workspace: controller-repo
        - name: ssh-directory
          workspace: gitlab-jenkins-csb-token
    - name: create-managed-repo
      params:
        - name: BASE_IMAGE
          value: 'registry.access.redhat.com/ubi9/ubi:latest'
        - name: GIT_USER_NAME
          value: ccit-test
        - name: GIT_USER_EMAIL
          value: ccit-test@redhat.com
        - name: GIT_SCRIPT
          value: >
            dnf install -y --disableplugin=subscription-manager openldap-clients
            bash jq 

            git config --global --add safe.directory $(workspaces.source.path)

            cd $(workspaces.source.path)


            ssh-keyscan -t ecdsa gitlab.cee.redhat.com >> ~/.ssh/known_hosts

            echo -e "Host gitlab.cee.redhat.com\n  IdentityFile /root/.ssh/id_rsa" >> ~/.ssh/config

            bash -x ./scripts/create_managed_repo.sh "$(params.team)"
            $(params.instance) $(params.roverGroup)
            $(workspaces.custom-workspace.path)/jenkins-csb-customers-token

        - name: USER_HOME
          value: /root
        - name: VERBOSE
          value: 'true'
      runAfter:
        - clone-jenkins-csb
      taskRef:
        kind: Task
        name: git-cli-with-workspace
      when:
        - input: $(tasks.gather-general-facts.results.customerRepoExists)
          operator: in
          values:
            - 'False'
      workspaces:
        - name: custom-workspace
          workspace: jenkins-csb-customers-token
        - name: source
          workspace: jenkins-csb-repo
        - name: ssh-directory
          workspace: gitlab-jenkins-csb-token
    - name: create-openshift-project
      params:
        - name: teamName
          value: $(params.team)
        - name: OCP_CLUSTER
          value: $(params.OCP_CLUSTER)
        - name: label-ns
          value: dno-gitops
      runAfter:
        - gather-general-facts
      taskRef:
        kind: Task
        name: create-openshift-project
      when:
        - input: $(tasks.gather-general-facts.results.projectExists)
          operator: in
          values:
            - 'False'
        - input: $(params.OCP_CLUSTER)
          operator: in
          values:
            - 'ocp-c1'
    - name: clone-managed-secrets
      params:
        - name: url
          value: >-
            git@gitlab.cee.redhat.com:ccit/jenkins-csb-tooling/managed-secrets.git
        - name: revision
          value: main
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:681dc67d2aa1dbecbf65ecd229c8b181dae533bf14b07543c1aeead36aed2198
        - name: userHome
          value: /home/git
      runAfter:
        - gather-general-facts
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: managed-secrets-repo
        - name: ssh-directory
          workspace: gitlab-jenkins-csb-token
    - name: push-saml-key
      params:
        - name: BASE_IMAGE
          value: 'registry.access.redhat.com/ubi9/ubi:latest'
        - name: GIT_USER_NAME
          value: ccit-test
        - name: GIT_USER_EMAIL
          value: ccit-test@redhat.com
        - name: GIT_SCRIPT
          value: >
            git config --global --add safe.directory $(workspaces.source.path)

            cd $(workspaces.source.path)

            SAML_FILE="secrets/saml/jenkins-csb-$(params.team)/$(params.instance)/keystore.jks"


            # checking if saml keys were already pushed if [ -e "$SAML_FILE" ];
            then
              echo "SAML keys already exist in managed-secrets repo, skipping"
              exit 0
            fi

            ls -l 

            dnf install java-17-openjdk -y

            ssh-keyscan -t ecdsa gitlab.cee.redhat.com >> ~/.ssh/known_hosts


            echo -e "Host gitlab.cee.redhat.com\n  IdentityFile /root/.ssh/id_rsa" >> ~/.ssh/config

            
            bash -x ./create-saml-keys.sh "jenkins-csb-$(params.team)"
            $(params.instance)


            git add .


            git commit -m "Pipeline : New key for
            jenkins-csb-$(params.team)/$(params.instance)" 


            git push origin HEAD:main 
        - name: USER_HOME
          value: /root
        - name: VERBOSE
          value: 'true'
      runAfter:
        - clone-managed-secrets
      taskRef:
        kind: Task
        name: git-cli-with-workspace
      when:
        - input: $(params.controllerBranch)
          operator: in
          values:
            - main
      workspaces:
        - name: custom-workspace
          workspace: jenkins-csb-customers-token
        - name: source
          workspace: managed-secrets-repo
        - name: ssh-directory
          workspace: gitlab-jenkins-csb-token
    - name: gather-general-facts
      params:
        - name: rover_group
          value: $(params.roverGroup)
        - name: teamName
          value: $(params.team)
        - name: instanceName
          value: $(params.instance)
        - name: controllerRepoBranch
          value: $(params.controllerBranch)
        - name: OCP_CLUSTER
          value: $(params.OCP_CLUSTER)
      taskRef:
        kind: Task
        name: gather-general-facts
  workspaces:
    - name: gitlab-jenkins-csb-token
    - name: jenkins-csb-customers-token
    - name: controller-repo
    - name: jenkins-csb-repo
    - name: managed-secrets-repo
    - name: dno-config-repo
