kind: Secret
apiVersion: v1
metadata:
  name: jenkins-quota-token
  annotations:
    avp.kubernetes.io/path: "apps/data/dno-secrets/dno-pipelines/jenkins-csb-deploy"
type: Opaque
stringData:
  jenkins-quota-token: <jenkins-quota-token>
