kind: Secret
apiVersion: v1
metadata:
  name: jenkins-csb-customers-token
  annotations:
    avp.kubernetes.io/path: "apps/data/dno-secrets/dno-pipelines/jenkins-csb-deploy"
type: Opaque
stringData:
  jenkins-csb-customers-token: <jenkins-csb-customers-token>
