kind: Secret
apiVersion: v1
metadata:
  name: gitlab-jenkins-csb-token
  annotations:
    avp.kubernetes.io/path: "apps/data/dno-secrets/dno-pipelines/jenkins-csb-deploy"
type: Opaque
stringData:
  id_rsa: <gitlab-auth>

