apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-csb-deploy
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-manage-services
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["taskruns"]
    verbs: ["get", "delete", "list"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "delete", "list", create, patch, update]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-csb-deploy-sa
subjects:
  - kind: ServiceAccount
    name: jenkins-csb-deploy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-manage-services
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-csb-deploy-edit-role
subjects:
  - kind: ServiceAccount
    name: jenkins-csb-deploy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
