apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-openshift-project
spec:
  params:
    - name: teamName
      type: string
    - name: label-ns
      type: string
    - name: OCP_CLUSTER
      type: string
  steps:
    - env:
        - name: JENKINS-TOKEN
          valueFrom:
            secretKeyRef:
              key: jenkins-quota-token
              name: jenkins-quota-token
      image: 'quay.io/openshift/origin-cli:latest'
      name: create-project
      script: >
        #!/usr/bin/env bash

        set -x

        echo "Creating project: jenkins-csb-$(params.teamName)" 


        set +x  

        printenv JENKINS-TOKEN > /tmp/token

        oc login --token=$(cat /tmp/token)
        --server="https://api.$(params.OCP_CLUSTER).prod.psi.redhat.com:6443"


        CURRENT_USER=$(oc whoami)

        set -x  


        echo -e "\n\Create Project: jenkins-csb-$(params.teamName)\n"


        if [ "$CURRENT_USER" = "system:serviceaccount:dno-jenkins-csb:jenkins"
        ]; then

            # Create the new project
            oc new-project "jenkins-csb-$(params.teamName)"
            oc adm policy add-role-to-group admin dno-admin -n "jenkins-csb-$(params.teamName)"

        else
            echo "Failed to create project jenkins-csb-'$(params.teamName)': Unexpected user $CURRENT_USER"
            exit 1
        fi


        # Install TKN Command. 

        dnf copr enable chmouel/tektoncd-cli -y > /dev/null 2>&1

        dnf install tektoncd-cli -y > /dev/null 2>&1


        tkn version 


        echo -e "\n\nLabel Project: jenkins-csb-$(params.teamName)\n"


        tkn pipeline start label-ns --showlog -p
        ns-to-label=jenkins-csb-"$(params.teamName)" -p
        labeling-ns=$(params.label-ns) -s ocp4admin -n tekton-tasks


        sleep 3

        if (oc get namespace "jenkins-csb-"$(params.teamName)""
        --show-labels|grep "argocd.argoproj.io/managed-by=$(params.label-ns)" >
        /dev/null 2>&1); then
            echo "Project jenkins-csb-$(params.teamName) was successfully labeled for $(params.label-ns)"
        else
            echo "Failed to label project jenkins-csb-"$(params.teamName)" for $(params.label-ns)"
            # exit 1
        fi
