apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - task.clean-pvc.yaml
  - serviceaccount.pipeline.yaml
  - secret.git-clone-ssh-directory-gitlab-deployments-jenkins-csb-controller.yaml
#  - egress.yaml
