kind: Secret
apiVersion: v1
metadata:
  name: git-clone-ssh-directory-gitlab-deployments-jenkins-csb-controller
  annotations:
    description: Reusable secret to clone ccit/deployments/jenkins-csb/controller
    avp.kubernetes.io/path: "apps/data/dno-secrets/dno-pipelines/jenkins-csb-deploy"
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: <gitlab-auth>
  known_hosts: |
    gitlab.cee.redhat.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDXAc+2x0Z5jMxGVk1J6rN5e1a1hA0L/xLrZMV8iAJmDU/QjlaCcFduF73TzUQnAQu55jpmx4WmBizkz5YqR5SIiJy9y4GXXpup6YKXketFVGJinphl66LMCKWH2nRmdJbe6nzNac8nS6ZKb2X9Oc3NbxgEQMtY5Q2bzPkEiOf4Etp3MInbi9AAJsdkRC9yKhrQcHAniBO5Ugkk6XtxuzW/TdismBto2JZoarsGAuBe4oVOXwfo6arbVE6P8HGH0XShwzFLkm1E92eckeE2/93PDYWm1vteJv5VT8Gr0acEkPX93TpqwL5MqKbbco7pFStuDe5SrJ4i36KV/aCl4Ixz
