apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: clean-pvc
spec:
  steps:
    - image: registry.redhat.io/ubi7/ubi-minimal
      name: wipe-pvc
      script: >
        #!/usr/bin/env bash

        clean_command="rm -rf
        $(workspaces.clone-directory.path)/{..?*,.[!.]*,*}"

        echo -e "Before cleaning:"

        ls -al $(workspaces.clone-directory.path)

        echo -e "\nCleaning PVC with: ${clean_command}"

        eval "$clean_command"

        echo -e "After cleaning:"

        ls -al $(workspaces.clone-directory.path)

        echo -e "\n##########\nPVC Wiped\n##########"
  workspaces:
    - name: clone-directory
