apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: genie
spec:
  params:
    - name: IMAGE_BUILD_ROOT
      type: string
      description: Build root inside cloned-sources workspace
      default: "."
    - name: IMAGE_URL
      type: string
      description: The full image URL to push, including the registry.
  workspaces:
    - name: cloned-sources
      description: Sources to build the image from
      mountPath: /workspace/cloned-sources
  stepTemplate:
    env:
      # https://access.redhat.com/solutions/6956010
      - name: "HOME"
        value: "/tekton/home"
  steps:
    - name: build-image
      image: "quay.io/buildah/stable:latest"
      env:
        - name: IMAGE_BUILD_ROOT
          value: "$(params.IMAGE_BUILD_ROOT)"
        - name: IMAGE_URL
          value: "$(params.IMAGE_URL)"
      workingDir: /workspace # https://access.redhat.com/solutions/6956010
      script: |
        #!/usr/bin/env bash
        # https://github.com/olivergondza/bash-strict-mode
        set -eEuo pipefail
        trap 's=$?; echo >&2 "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
        
        set -x
        
        cd "/workspace/cloned-sources/$IMAGE_BUILD_ROOT"
        buildah bud -t "$IMAGE_URL" .
        buildah push "$IMAGE_URL"
        
        echo "DONE"
    # TODO: Suppress to verify previous steps first
#    - name: run-script
#      image: "$(params.IMAGE_URL)"
#      imagePullPolicy: Always
#      script: |
#        #!/bin/sh
#        set -e
#        cd /
#        if [ -x ./script.sh ]; then
#          ./script.sh
#        else
#          echo "script.sh not found or not executable"
#          exit 1
#        fi
