apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: jenkins-csb-upgrade-image
  annotations:
    avp.kubernetes.io/path: "apps/data/dno-secrets/gitlab/dno-ops-prod"
stringData:
  username: dno-ops-prod
  password: <password>  # Added via Hashicorp Vault Plugin
