apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: jenkins-csb-upgrade
spec:
  params:
    - name: TEAM
      type: string
      description: 'Team name'
    - name: TENANT
      type: string
      description: 'Jenkins tenant'
    - name: NEW_VERSION
      type: string
      description: 'For example: 2.452.4'
  workspaces:
    - name: cloned-sources
      description: WS to share cloned sources with genie
    - name: clone-ssh-creds
      description: Mounted secret so git can clone private repo
  tasks:
    - name: clone-controller
      params:
        - name: revision
          value: main
        - name: url
          value: git@gitlab.cee.redhat.com:ccit/deployments/jenkins-csb/controller.git
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: cloned-sources
        - name: ssh-directory
          workspace: clone-ssh-creds
    - name: update-files
      runAfter:
        - clone-controller
      params:
        - name: TEAM
          value: $(params.TEAM)
        - name: TENANT
          value: $(params.TENANT)
        - name: NEW_VERSION
          value: $(params.NEW_VERSION)
      workspaces:
        - name: cloned-sources
          workspace: cloned-sources
      taskSpec:
        steps:
          - name: upgrade
            script: "/upgrade.sh"
            image: image-registry.openshift-image-registry.svc:5000/dno--pipeline/pl-jenkins-csb-upgrade-image:latest
