apiVersion: v1
kind: Secret
metadata:
  name: jenkins-csb-controller-repo-secret
  annotations:
    avp.kubernetes.io/path: "apps/data/dno-secrets/dno-pipelines/jenkins-csb-deploy"
type: Opaque
stringData:
  ssh-private-key: <gitlab-auth>
