apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: jenkins-csb-upgrade
  annotations:
    description: "Await JSON event and trigger the pipeline passing in the body fields as pipeline run parameters"
spec:
  serviceAccountName: pipeline
  triggers:
    - name: jenkins-csb-upgrade
      bindings:
        - name: TEAM
          value: $(body.team_name)
        - name: TENANT
          value: $(body.tenant_name)
        - name: NEW_VERSION
          value: $(body.version)
      template:
        spec:
          params:
            - name: TEAM
            - name: TENANT
            - name: NEW_VERSION
          resourcetemplates:
            - apiVersion: tekton.dev/v1beta1
              kind: PipelineRun
              metadata:
                generateName: jenkins-csb-upgrade-$(tt.params.TEAM)--$(tt.params.TENANT)--$(tt.params.NEW_VERSION)-
              spec:
                pipelineRef:
                  name: jenkins-csb-upgrade
                params:
                  - name: TEAM
                    value: $(tt.params.TEAM)
                  - name: TENANT
                    value: $(tt.params.TENANT)
                  - name: NEW_VERSION
                    value: $(tt.params.NEW_VERSION)
