apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jenkins-csb-upgrade
spec:
  params:
    - name: TEAM
      type: string
    - name: TENANT
      type: string
    - name: NEW_VERSION
      type: string
  steps:
    - name: clone-repo
      image: 'registry.access.redhat.com/ubi9/ubi:latest'
      script: |
        #!/usr/bin/env bash
        # https://github.com/olivergondza/bash-strict-mode
        set -eEuo pipefail
        trap 's=$?; echo >&2 "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
  
        DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

        id; ls -ldA /

        echo "UPGRADING $(params.TEAM) $(params.TENANT) $(params.NEW_VERSION)"

        dnf install -y --disableplugin=subscription-manager \
            git \
            kustomize
        
        git config --global user.email "dno-pipelines-jenkins-csb-upgrade@example.com"
        git config --global user.name "dno-pipelines-jenkins-csb-upgrade"
        
        git clone --branch main --single-branch "git@gitlab.cee.redhat.com:ccit/deployments/jenkins-csb/controller.git" /workspace/repo
        cd /workspace/repo

        git status
        ls -l

        git push
      volumeMounts:
        - name: ssh-key-volume
          mountPath: /root/.ssh
          readOnly: true
      securityContext:
        runAsUser: 0
  volumes:
    - name: ssh-key-volume
      secret:
        secretName: jenkins-csb-controller-repo-secret
