apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - genie.task.yaml
  - image-bc.yaml
  - image-is.yaml
  - image-git-clone-secret.yaml

  - jenkins-csb-upgrade-pipeline.yaml
  - jenkins-csb-upgrade-pipeline-root.yaml  # TODO: Delete once done
  - jenkins-csb-upgrade-task.yaml
  - jenkins-csb-controller-repo-secret.yaml

  - jenkins-csb-upgrade-event-listener.yaml
  - jenkins-csb-upgrade-event-listener-custom-sa.yaml  # TODO: Delete once done
  - tekton-event-listener-rbac.yaml
