apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-event-listener
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-event-listener
rules:
  # Permissions for every EventListener deployment to function
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["clusterinterceptors", "eventlisteners", "triggerbindings", "triggertemplates", "interceptors", "triggers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  # Permissions to create resources in associated TriggerTemplates
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns", "taskruns"]
    verbs: ["create"]
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "create", "patch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-event-listener
subjects:
  - kind: ServiceAccount
    name: tekton-event-listener
roleRef:
  kind: Role
  name: tekton-event-listener
  apiGroup: rbac.authorization.k8s.io
