apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: documentation-pipeline-template
spec:
  params:
    - name: gitrevision
    - name: gitrepositoryurl
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: documentation-pipeline-run-
      spec:
        pipelineRef:
          name: documentation-pipeline
        podTemplate:
          securityContext:
            fsGroup: 65532
            runAsNonRoot: true
            runAsUser: 65532
        workspaces:
        - name: documentation-workspace
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              volumeMode: Filesystem
              storageClassName: dynamic-nfs
              resources:
                requests:
                  storage: 1Gi
        params:
        - name: gitrevision
          value: $(tt.params.gitrevision)
        - name: gitrepositoryurl
          value: $(tt.params.gitrepositoryurl)
