#Used https://tekton.dev/docs/getting-started/
#to figure out most of this
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: documentation-pipeline
spec:
  workspaces:
    - name: documentation-workspace
  params:
    - name: gitrevision
      type: string
      default: main
    - name: gitrepositoryurl
      type: string
      default: "https://gitlab.cee.redhat.com/ccit/documentation-pipeline.git"
  tasks:
    - name: clone-documentation
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: $(params.gitrepositoryurl)
        - name: revision
          value: $(params.gitrevision)
        - name: sslVerify
          value: 'false'
        - name: userHome
          value: /tekton/home
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:aa2599a70c14b4f30c9959f6ddafc2510180764d9464e6e2ec5f2147a0a0bf80
      workspaces:
        - name: output
          workspace: documentation-workspace
    - name: show-cloned-repo
      runAfter:
        - clone-documentation
      taskRef:
        kind: Task
        name: show-repo-contents
      workspaces:
        - name: source
          workspace: documentation-workspace
  finally:
    - name: clean-pvc
      taskRef:
        kind: Task
        name: clean-pvc
      workspaces:
        - name: clone-directory
          workspace: documentation-workspace
