apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../base/gitlab-monitor
patches:
  # Configure email settings for live deployment
  - target:
      group: tekton.dev
      version: v1
      kind: Pipeline
      name: gitlab-monitor-pipeline
    path: patches/gitlab-monitor-pipeline.jpatch.yaml 