# Example IntegrationTestScenario for Application coffee / component coffee-break.
---
apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  name: coffee-break-verify-hello-world
  namespace: sfathii-tenant
spec:
  application: coffee
  contexts:
    - description: Verify coffee-break image prints Hello World
      name: application
  resolverRef:
    resolver: git
    resourceKind: pipeline
    params:
      - name: url
        value: https://github.com/tomswallaRH/dno-pipelines.git
      - name: revision
        value: main
      - name: pathInRepo
        value: applications/coffee/integration/verify-hello.yaml
