apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: coffee-binding
spec:
  params:
    - name: gitrevision
      value: master
    - name: gitrepositoryurl
      value: 'https://github.com/tektoncd/triggers'
