apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: coffee-break
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: coffee-binding
      template:
        ref: coffee-break