apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: coffee-break
spec:
  params:
    - name: gitrevision
    - name: gitrepositoryurl
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: coffee-break-
        labels:
          tekton.dev/pipeline: coffee-break
        namespace: dno-pipelines-dev
      spec:
        pipelineRef:
          name: coffee-break
        timeout: 1h0m0s
        workspaces:
          - name: ssh-creds
            secret:
              secretName: coffee-ssh
          - name: clone-directory
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
                storageClassName: dynamic-nfs
                volumeMode: Filesystem
