kind: CronJob
apiVersion: batch/v1
metadata:
  name: cron-coffee
spec:
  schedule: 0 14 * * 2
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: trigger-coffee
              image: curlimages/curl
              command: 
                - curl
              args:
                - '-X'
                - POST
                - '--data'
                - '{}'
                - PLACEHOLDER #URL Placeholder, replaced via json patch
          restartPolicy: OnFailure
