apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - coffee-break.pipeline.yaml
  - sendmail.task.yaml
  - execute-coffee-break.task.yaml
  - coffee-ssh.secret.yaml
  - coffee-break.eventlistener.yaml
  - coffee-break.triggertemplate.yaml
  - coffee-binding.triggerbinding.yaml
  - cron-coffee.cronjob.yaml
  - coffee-pvc.yaml
#  - task.clean-pvc.yaml - in base/general