apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    openshift.io/installed-from: tektonhub
    tekton.dev/categories: Messaging
    tekton.dev/displayName: send mail
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/platforms: 'linux/amd64,linux/s390x,linux/ppc64le,linux/arm64'
    tekton.dev/tags: mail
  name: sendmail
  labels:
    app.kubernetes.io/version: '0.1'
spec:
  description: This task sends a simple email to receivers via the Red Hat SMTP server
  params:
    - description: plain text email subject
      name: subject
      type: string
    - description: plain text email body
      name: body
      type: string
    - description: sender email address
      name: sender
      type: string
    - description: recipient email addresses (space delimited list)
      name: recipients
      type: string
  results:
    - description: The current date in unix timestamp format
      name: sendmail
      type: string
  steps:
    - env:
        - name: SERVER
          value: smtp.corp.redhat.com
        - name: PORT
          value: '25'
      image: registry.redhat.io/ubi8/python-36
      name: send
      script: |
        #!/usr/bin/env python3
        import smtplib, ssl, os
        port = os.getenv('PORT')
        smtp_server = os.getenv('SERVER')
        sender_email = "$(params.sender)"
        receiver_emails = "$(params.recipients)"
        message = f"""\
        Subject: $(params.subject)
        To: {receiver_emails}
        From: {sender_email}

        $(params.body)"""
        print(message)
        server = smtplib.SMTP(smtp_server, port)
        for receiver in receiver_emails.split(' '):
            server.sendmail(sender_email, receiver, message.encode('utf-8'))
        server.quit()
