apiVersion: tenant.paas.redhat.com/v1alpha1
kind: TenantEgress
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-options: Delete=false, Prune=false
spec:
  egress:
    - to:
        cidrSelector: 172.0.0.0/8
      type: Allow
    - to:
        cidrSelector: 10.0.0.0/9
      type: Allow
    - to:
        cidrSelector: 52.218.128.0/17
      type: Allow
    - to:
        cidrSelector: 52.92.128.0/17
      type: Allow
    - to:
        cidrSelector: 52.216.0.0/15
      type: Allow
    - to:
        dnsName: quay.io
      type: Allow
    - to:
        dnsName: raw.githubusercontent.com
      type: Allow
    - to:
        dnsName: mirrors.fedoraproject.org
      type: Allow
    - to:
        dnsName: fedoraproject.org
      type: Allow
    - to:
        dnsName: cdn.quay.io
      type: Allow
    - to:
        dnsName: cdn01.quay.io
      type: Allow
    - to:
        dnsName: cdn02.quay.io
      type: Allow
    - to:
        dnsName: cdn03.quay.io
      type: Allow
    - to:
        dnsName: quay.io
      type: Allow
    - to:
        dnsName: raw.githubusercontent.com
      type: Allow
    - to:
        dnsName: mirrors.fedoraproject.org
      type: Allow
    - to:
        dnsName: fedoraproject.org
      type: Allow
    - to:
        dnsName: cdn.quay.io
      type: Allow
    - to:
        dnsName: cdn01.quay.io
      type: Allow
    - to:
        dnsName: cdn02.quay.io
      type: Allow
    - to:
        dnsName: cdn03.quay.io
      type: Allow
    - to:
        dnsName: fedora.xfree.com.ar
      type: Allow
    - to:
        dnsName: mirror.alwyzon.net
      type: Allow
    - to:
        dnsName: ap.edge.kernel.org
      type: Allow
    - to:
        dnsName: au.mirrors.cicku.me
      type: Allow
    - to:
        dnsName: fedora.melbourneitmirror.net
      type: Allow
    - to:
        dnsName: fedora.mirror.crucial.com.au
      type: Allow
    - to:
        dnsName: fedora.mirror.digitalpacific.com.au
      type: Allow
    - to:
        dnsName: ftp.iinet.net.au
      type: Allow
    - to:
        dnsName: ftp.swin.edu.au
      type: Allow
    - to:
        dnsName: gsl-syd.mm.fcix.net
      type: Allow
    - to:
        dnsName: lchs.mm.fcix.net
      type: Allow
    - to:
        dnsName: mirror.aarnet.edu.au
      type: Allow
    - to:
        dnsName: mirror.realcompute.io
      type: Allow
    - to:
        dnsName: syd.mirror.rackspace.com
      type: Allow
    - to:
        dnsName: mirror.yer.az
      type: Allow
    - to:
        dnsName: fedora.cu.be
      type: Allow
    - to:
        dnsName: fedora.ipacct.com
      type: Allow
    - to:
        dnsName: fedora.linuxman.biz
      type: Allow
    - to:
        dnsName: mirror.host.ag
      type: Allow
    - to:
        dnsName: mirrors.neterra.net
      type: Allow
    - to:
        dnsName: mirrors.netix.net
      type: Allow
    - to:
        dnsName: mirror.telepoint.bg
      type: Allow
    - to:
        dnsName: br.mirrors.cicku.me
      type: Allow
    - to:
        dnsName: fedora.c3sl.ufpr.br
      type: Allow
    - to:
        dnsName: linorg.usp.br
      type: Allow
    - to:
        dnsName: mirror.datacenter.by
      type: Allow
    - to:
        dnsName: ca.mirrors.cicku.me
      type: Allow
    - to:
        dnsName: fedora.mirror.gtcomm.net
      type: Allow
    - to:
        dnsName: fedora.mirror.iweb.com
      type: Allow
    - to:
        dnsName: mirror.cpsc.ucalgary.ca
      type: Allow
    - to:
        dnsName: mirror.csclub.uwaterloo.ca
      type: Allow
    - to:
        dnsName: mirror.dst.ca
      type: Allow
    - to:
        dnsName: mirror.its.dal.ca
      type: Allow
    - to:
        dnsName: mirror.layeronline.com
      type: Allow
    - to:
        dnsName: mirror.xenyth.net
      type: Allow
    - to:
        dnsName: muug.ca
      type: Allow
    - to:
        dnsName: ch.mirrors.cicku.me
      type: Allow
    - to:
        dnsName: ipng.mm.fcix.net
      type: Allow
    - to:
        dnsName: linuxsoft.cern.ch
      type: Allow
    - to:
        dnsName: mirror.init7.net
      type: Allow
    - to:
        dnsName: pkg.adfinis.com
      type: Allow
    - to:
        dnsName: pkg.adfinis-on-exoscale.ch
      type: Allow
    - to:
        dnsName: mirror.nyist.edu.cn
      type: Allow
    - to:
        dnsName: mirrors.163.com
      type: Allow
    - to:
        dnsName: mirrors.huaweicloud.com
      type: Allow
    - to:
        dnsName: mirrors.jlu.edu.cn
      type: Allow
    - to:
        dnsName: mirrors.neusoft.edu.cn
      type: Allow
    - to:
        dnsName: mirrors.qlu.edu.cn
      type: Allow
    - to:
        dnsName: mirrors.sohu.com
      type: Allow
    - to:
        dnsName: mirrors.tuna.tsinghua.edu.cn
      type: Allow
    - to:
        dnsName: mirrors.yun-idc.com
      type: Allow
    - to:
        dnsName: mirrors.zju.edu.cn
      type: Allow
    - to:
        dnsName: edgeuno-bog2.mm.fcix.net
      type: Allow
    - to:
        dnsName: ftp.fi.muni.cz
      type: Allow
    - to:
        dnsName: ftp.sh.cvut.cz
      type: Allow
    - to:
        dnsName: mirror.karneval.cz
      type: Allow
    - to:
        dnsName: mirrors.nic.cz
      type: Allow
    - to:
        dnsName: de.mirrors.cicku.me
      type: Allow
    - to:
        dnsName: fedora.tu-chemnitz.de
      type: Allow
    - to:
        dnsName: ftp.agdsn.de
      type: Allow
    - to:
        dnsName: ftp.fau.de
      type: Allow
    - to:
        dnsName: ftp.halifax.rwth-aachen.de
      type: Allow
    - to:
        dnsName: ftp.informatik.uni-frankfurt.de
      type: Allow
    - to:
        dnsName: ftp.plusline.net
      type: Allow
    - to:
        dnsName: ftp-stud.hs-esslingen.de
      type: Allow
    - to:
        dnsName: ftp.uni-bayreuth.de
      type: Allow
    - to:
        dnsName: ftp.uni-kl.de
      type: Allow
    - to:
        dnsName: ftp.uni-stuttgart.de
      type: Allow
    - to:
        dnsName: level66.mm.fcix.net
      type: Allow
    - to:
        dnsName: mirror.23m.com
      type: Allow
    - to:
        dnsName: mirror.de.leaseweb.net
      type: Allow
    - to:
        dnsName: mirror.dogado.de
      type: Allow
    - to:
        dnsName: mirror.euserv.net
      type: Allow
    - to:
        dnsName: mirror.netzwerge.de
      type: Allow
    - to:
        dnsName: mirrors.n-ix.net
      type: Allow
    - to:
        dnsName: mirrors.xtom.de
      type: Allow
    - to:
        dnsName: mirror.netsite.dk
      type: Allow
    - to:
        dnsName: mirrors.dotsrc.org
      type: Allow
    - to:
        dnsName: stix.mm.fcix.net
      type: Allow
    - to:
        dnsName: mirror.cedia.org.ec
      type: Allow
    - to:
        dnsName: mirrors.xtom.ee
      type: Allow
    - to:
        dnsName: es.mirrors.cicku.me
      type: Allow
    - to:
        dnsName: es-mirrors.evowise.com
      type: Allow
    - to:
        dnsName: ftp.cica.es
      type: Allow
    - to:
        dnsName: mirror.raiolanetworks.com
      type: Allow
    - to:
        dnsName: mirror.uv.es
      type: Allow
    - to:
        dnsName: ftp.funet.fi
      type: Allow
    - to:
        dnsName: distrib-coffee.ipsl.jussieu.fr
      type: Allow
    - to:
        dnsName: fr2.rpmfind.net
      type: Allow
    - to:
        dnsName: ftp.lip6.fr
      type: Allow
    - to:
        dnsName: mirror.fedora.ikoula.com
      type: Allow
    - to:
        dnsName: mirror.in2p3.fr
      type: Allow
    - to:
        dnsName: ask4.mm.fcix.net
      type: Allow
    - to:
        dnsName: b4sh.mm.fcix.net
      type: Allow
    - to:
        dnsName: creeperhost.mm.fcix.net
      type: Allow
    - to:
        dnsName: divergentnetworks.mm.fcix.net
      type: Allow
    - to:
        dnsName: fedora.mirrorservice.org
      type: Allow
    - to:
        dnsName: gb.mirrors.cicku.me
      type: Allow
    - to:
        dnsName: mirror.bytemark.co.uk
      type: Allow
    - to:
        dnsName: mirror.ox.ac.uk
      type: Allow
    - to:
        dnsName: mirrors.20i.com
      type: Allow
    - to:
        dnsName: uk-mirrors.evowise.com
      type: Allow
    - to:
        dnsName: ftp.cc.uoc.gr
      type: Allow
    - to:
        dnsName: ftp.ntua.gr
      type: Allow
    - to:
        dnsName: ftp.otenet.gr
      type: Allow
    - to:
        dnsName: hkg.mirror.rackspace.com
      type: Allow
    - to:
        dnsName: hk.mirrors.cicku.me
      type: Allow
    - to:
        dnsName: mirror.szerverem.hu
      type: Allow
    - to:
        dnsName: repo.ugm.ac.id
      type: Allow
    - to:
        dnsName: mirror.isoc.org.il
      type: Allow
    - to:
        dnsName: in.mirrors.cicku.me
      type: Allow
    - to:
        dnsName: mirror.cse.iitk.ac.in
      type: Allow
    - to:
        dnsName: fedora.mirror.garr.it
      type: Allow
    - to:
        dnsName: ftp.iij.ad.jp
      type: Allow
    - to:
        dnsName: ftp.iij.ad.jp
      type: Allow
    - to:
        dnsName: ftp.kddilabs.jp
      type: Allow
    - to:
        dnsName: ftp.riken.jp
      type: Allow
    - to:
        dnsName: ftp.yz.yamagata-u.ac.jp
      type: Allow
    - to:
        dnsName: jp.mirrors.cicku.me
      type: Allow
    - to:
        dnsName: linux.yz.yamagata-u.ac.jp
      type: Allow
    - to:
        dnsName: repo.jing.rocks
      type: Allow
    - to:
        dnsName: www.ftp.ne.jp
      type: Allow
    - to:
        dnsName: fedora.mirror.liquidtelecom.com
      type: Allow
    - to:
        dnsName: fedora-secondary.mirror.liquidtelecom.com
      type: Allow
    - to:
        dnsName: ftp.kaist.ac.kr
      type: Allow
    - to:
        dnsName: ftp.kaist.ac.kr
      type: Allow
    - to:
        dnsName: kr.mirrors.cicku.me
      type: Allow
    - to:
        dnsName: mirror.hoster.kz
      type: Allow
    - to:
        dnsName: mirror.ps.kz
      type: Allow
    - to:
        dnsName: mirror.vpsnet.com
      type: Allow
    - to:
        dnsName: fedora.mirror.root.lu
      type: Allow
    - to:
        dnsName: mirror.marwan.ma
      type: Allow
    - to:
        dnsName: mirror.ihost.md
      type: Allow
    - to:
        dnsName: repo.fedora.md
      type: Allow
    - to:
        dnsName: mirrors.ipserverone.com
      type: Allow
    - to:
        dnsName: eu.edge.kernel.org
      type: Allow
    - to:
        dnsName: ftp.nluug.nl
      type: Allow
    - to:
        dnsName: ftp.tudelft.nl
      type: Allow
    - to:
        dnsName: mirror.i3d.net
      type: Allow
    - to:
        dnsName: mirror.nl.leaseweb.net
      type: Allow
    - to:
        dnsName: mirror.nl.mirhosting.net
      type: Allow
    - to:
        dnsName: mirrors.hostiserver.com
      type: Allow
    - to:
        dnsName: mirror.theory7.net
      type: Allow
    - to:
        dnsName: nl.mirrors.cicku.me
      type: Allow
    - to:
        dnsName: fedora.uib.no
      type: Allow
    - to:
        dnsName: mirror.2degrees.nz
      type: Allow
    - to:
        dnsName: ucmirror.canterbury.ac.nz
      type: Allow
    - to:
        dnsName: mirror.rise.ph
      type: Allow
    - to:
        dnsName: ftp.icm.edu.pl
      type: Allow
    - to:
        dnsName: mirror.chmuri.net
      type: Allow
    - to:
        dnsName: mirroronet.pl
      type: Allow
    - to:
        dnsName: ftp.dei.uc.pt
      type: Allow
    - to:
        dnsName: mirrors.ptisp.pt
      type: Allow
    - to:
        dnsName: mirrors.up.pt
      type: Allow
    - to:
        dnsName: ftp.ines.lug.ro
      type: Allow
    - to:
        dnsName: mirrors.chroot.ro
      type: Allow
    - to:
        dnsName: mirrors.nav.ro
      type: Allow
    - to:
        dnsName: mirrors.nxthost.com
      type: Allow
    - to:
        dnsName: mirror.etf.bg.ac.rs
      type: Allow
    - to:
        dnsName: fedora-mirror02.rbc.ru
      type: Allow
    - to:
        dnsName: mirror.hyperdedic.ru
      type: Allow
    - to:
        dnsName: mirror.linux-ia64.org
      type: Allow
    - to:
        dnsName: mirror.yandex.ru
      type: Allow
    - to:
        dnsName: ru.mirrors.cicku.me
      type: Allow
    - to:
        dnsName: mirror.accum.se
      type: Allow
    - to:
        dnsName: mirror.bahnhof.net
      type: Allow
    - to:
        dnsName: download.nus.edu.sg
      type: Allow
    - to:
        dnsName: mirror.freedif.org
      type: Allow
    - to:
        dnsName: sg.mirrors.cicku.me
      type: Allow
    - to:
        dnsName: ftp.upjs.sk
      type: Allow
    - to:
        dnsName: mirror2.totbb.net
      type: Allow
    - to:
        dnsName: linus.iyte.edu.tr
      type: Allow
    - to:
        dnsName: fedora.cs.nctu.edu.tw
      type: Allow
    - to:
        dnsName: fedora.cs.nycu.edu.tw
      type: Allow
    - to:
        dnsName: free.nchc.org.tw
      type: Allow
    - to:
        dnsName: mirror.twds.com.tw
      type: Allow
    - to:
        dnsName: tw.mirrors.cicku.me
      type: Allow
    - to:
        dnsName: fastmirror.pp.ua
      type: Allow
    - to:
        dnsName: fedora.ip-connect.info
      type: Allow
    - to:
        dnsName: fedora.ip-connect.vn.ua
      type: Allow
    - to:
        dnsName: ftp.colocall.net
      type: Allow
    - to:
        dnsName: repo.hyron.dev
      type: Allow
    - to:
        dnsName: abqix.mm.fcix.net
      type: Allow
    - to:
        dnsName: atl.mirrors.knownhost.com
      type: Allow
    - to:
        dnsName: codingflyboy.mm.fcix.net
      type: Allow
    - to:
        dnsName: cofractal-ewr.mm.fcix.net
      type: Allow
    - to:
        dnsName: cofractal-sea.mm.fcix.net
      type: Allow
    - to:
        dnsName: coresite.mm.fcix.net
      type: Allow
    - to:
        dnsName: dfw.mirror.rackspace.com
      type: Allow
    - to:
        dnsName: download-cc-rdu01.fedoraproject.org
      type: Allow
    - to:
        dnsName: download-ib01.fedoraproject.org
      type: Allow
    - to:
        dnsName: fedora.mirror.constant.com
      type: Allow
    - to:
        dnsName: forksystems.mm.fcix.net
      type: Allow
    - to:
        dnsName: ftp-chi.osuosl.org
      type: Allow
    - to:
        dnsName: ftp-nyc.osuosl.org
      type: Allow
    - to:
        dnsName: ftp-osl.osuosl.org
      type: Allow
    - to:
        dnsName: ftp.usf.edu
      type: Allow
    - to:
        dnsName: ftp.ussg.iu.edu
      type: Allow
    - to:
        dnsName: iad.mirror.rackspace.com
      type: Allow
    - to:
        dnsName: ima.mm.fcix.net
      type: Allow
    - to:
        dnsName: irltoolkit.mm.fcix.net
      type: Allow
    - to:
        dnsName: ix-denver.mm.fcix.net
      type: Allow
    - to:
        dnsName: la-mirrors.evowise.com
      type: Allow
    - to:
        dnsName: linux.mirrors.es.net
      type: Allow
    - to:
        dnsName: mirror.chpc.utah.edu
      type: Allow
    - to:
        dnsName: mirror.cogentco.com
      type: Allow
    - to:
        dnsName: mirror.cs.princeton.edu
      type: Allow
    - to:
        dnsName: mirror.cs.siue.edu
      type: Allow
    - to:
        dnsName: mirror.facebook.net
      type: Allow
    - to:
        dnsName: mirror.fcix.net
      type: Allow
    - to:
        dnsName: mirrorfedora.math.princeton.edu
      type: Allow
    - to:
        dnsName: mirror.genesisadaptive.com
      type: Allow
    - to:
        dnsName: mirror.lax.adaptivedatanetworks.com
      type: Allow
    - to:
        dnsName: mirror.lstn.net
      type: Allow
    - to:
        dnsName: mirror.metrocast.net
      type: Allow
    - to:
        dnsName: mirror.nodesdirect.com
      type: Allow
    - to:
        dnsName: mirror.pilotfiber.com
      type: Allow
    - to:
        dnsName: mirrorsecondary.math.princeton.edu
      type: Allow
    - to:
        dnsName: mirror.servaxnet.com
      type: Allow
    - to:
        dnsName: mirror.sfo12.us.leaseweb.net
      type: Allow
    - to:
        dnsName: mirror.siena.edu
      type: Allow
    - to:
        dnsName: mirrors.lug.mtu.edu
      type: Allow
    - to:
        dnsName: mirrors.mit.edu
      type: Allow
    - to:
        dnsName: mirrors.oit.uci.edu
      type: Allow
    - to:
        dnsName: mirrors.rit.edu
      type: Allow
    - to:
        dnsName: mirror.steadfastnet.com
      type: Allow
    - to:
        dnsName: mirrors.tscak.com
      type: Allow
    - to:
        dnsName: mirrors.xmission.com
      type: Allow
    - to:
        dnsName: mirror.tornadovps.com
      type: Allow
    - to:
        dnsName: mirror.umd.edu
      type: Allow
    - to:
        dnsName: mirror.uoregon.edu
      type: Allow
    - to:
        dnsName: mirror.us.leaseweb.net
      type: Allow
    - to:
        dnsName: mirror.us-midwest-1.nexcess.net
      type: Allow
    - to:
        dnsName: mirror.us.mirhosting.net
      type: Allow
    - to:
        dnsName: mirror.web-ster.com
      type: Allow
    - to:
        dnsName: mnvoip.mm.fcix.net
      type: Allow
    - to:
        dnsName: na.edge.kernel.org
      type: Allow
    - to:
        dnsName: nnenix.mm.fcix.net
      type: Allow
    - to:
        dnsName: nocix.mm.fcix.net
      type: Allow
    - to:
        dnsName: nullroute.mm.fcix.net
      type: Allow
    - to:
        dnsName: ny-mirrors.evowise.com
      type: Allow
    - to:
        dnsName: ohioix.mm.fcix.net
      type: Allow
    - to:
        dnsName: opencolo.mm.fcix.net
      type: Allow
    - to:
        dnsName: ord.mirror.rackspace.com
      type: Allow
    - to:
        dnsName: packages.oit.ncsu.edu
      type: Allow
    - to:
        dnsName: paducahix.mm.fcix.net
      type: Allow
    - to:
        dnsName: pubmirror1.math.uh.edu
      type: Allow
    - to:
        dnsName: pubmirror3.math.uh.edu
      type: Allow
    - to:
        dnsName: ridgewireless.mm.fcix.net
      type: Allow
    - to:
        dnsName: ryamer.mm.fcix.net
      type: Allow
    - to:
        dnsName: sjc.mirror.rackspace.com
      type: Allow
    - to:
        dnsName: southfront.mm.fcix.net
      type: Allow
    - to:
        dnsName: us.mirrors.cicku.me
      type: Allow
    - to:
        dnsName: uvermont.mm.fcix.net
      type: Allow
    - to:
        dnsName: veronanetworks.mm.fcix.net
      type: Allow
    - to:
        dnsName: volico.mm.fcix.net
      type: Allow
    - to:
        dnsName: www.gtlib.gatech.edu
      type: Allow
    - to:
        dnsName: ziply.mm.fcix.net
      type: Allow
    - to:
        dnsName: espejito.fder.edu.uy
      type: Allow
    - to:
        dnsName: mirror.digistar.vn
      type: Allow
    - to:
        dnsName: fedora.is.co.za
      type: Allow
    - to:
        dnsName: cdn-ubi.redhat.com
      type: Allow
    - to:
        dnsName: gitlab.cee.redhat.com
      type: Allow
    - to:
        cidrSelector: 0.0.0.0/0
      type: Deny
