kind: Secret
apiVersion: v1
metadata:
  name: images-pass-token
  annotations:
    avp.kubernetes.io/path: "apps/data/dno-secrets/dno-pipelines/jenkins-image-builder" 
stringData:
  .dockerconfigjson: |-
    {
      "auths": {
        "images.paas.redhat.com": {
          "auth": "<images-pass-token>",
          "email": ""
        }
      }
    }
type: kubernetes.io/dockerconfigjson