apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-jenkins-csb-version
spec:
  params:
    - description: 'New Jenkins CSB version, e.g., X.Y.Z'
      name: new-version
      type: string
    - description: 'Old Jenkins CSB version to replace, e.g., W.V.U'
      name: old-version
      type: string
  steps:
    - image: 'registry.access.redhat.com/ubi8/ubi:latest'
      name: update-jenkins-version
      resources: {}
      script: >
        #!/usr/bin/env bash

        set -ex

        echo "updating the jenkins-csb-version from $(params.old-version) to $(params.new-version) ."

        # Navigate to the source workspace

        cd $(workspaces.source.path)


        # Update Jenkins version

        bash -x ./scripts/update-version.sh --version $(params.new-version)


        cat image-app/Dockerfile

        cat image-base/jenkins-csb-versions.yaml
  workspaces:
    - description: Workspace containing the source code and scripts
      name: source