apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: hello-world
  namespace: sfathii-tenant
spec:
  application: coffee
  componentName: hello-world
  containerImage: quay.io/redhat-user-workloads/sfathii-tenant/coffee/hello-world
  source:
    git:
      url: https://github.com/tomswallaRH/dno-pipelines
      revision: main
      context: hello-world
      dockerfileUrl: Containerfile
