apiVersion: v1
data:
  template: "apiVersion: v1\nkind: Pod\nmetadata:\n  name: replaceme-rsync-reciever\nspec:\n
    \ containers:\n  - name: replaceme-rsync-reciever\n    image: quay.io/openshift/origin-cli:4.20\n
    \   resources:\n     limits:\n       cpu: 1\n       memory: 16Gi\n
    \   # Just spin & wait forever\n    command: [ \"/bin/bash\", \"-c\", \"--\" ]\n
    \   args: [ \"while true; do sleep 30; done;\" ]\n    volumeMounts:\n      - mountPath:
    /var/lib/jenkins\n        name: jenkins-data\n  volumes:\n  - name: jenkins-data\n
    \   persistentVolumeClaim:\n      claimName: replaceme-jenkins\n    "
kind: ConfigMap
metadata:
  name: dummy-pod
