#/# Security concern
kind: Secret
apiVersion: v1
metadata:
  name: controller-repo-ssh
  annotations:
    avp.kubernetes.io/path: "apps/data/dno-secrets/dno-pipelines/jenkins-csb-deploy"
type: Opaque
stringData:
  id_rsa: <gitlab-auth>
#/ Security concern
