kind: Secret
apiVersion: v1
metadata:
  name: jenkins-csb-serviceaccounts
  annotations:
    avp.kubernetes.io/path: "apps/data/dno-secrets/dno-pipelines/jenkins-csb-pvc-migration"
type: Opaque
stringData:
  dno.ocp-hub: <jenkins-csb-edit-dno>
  ocp-c1: <jenkins-ocp-c1>
