apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: scale-1
spec:
  params:
  - description: kubeconfig file name
    name: filename
    type: string
  - description: project name
    name: project
    type: string
  - description: tenant name
    name: tenant
    type: string
  - description: name of the cluster
    name: cluster
    type: string
  steps:
  - image: quay.io/openshift/origin-cli:4.20
    name: dest-source-1
    resources: {}
    script: |
      #!/usr/bin/env bash
      set -euo pipefail
      trap 's=$?; echo >&2 "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
      export KUBECONFIG="$(workspaces.input.path)/$(inputs.params.cluster)/$(inputs.params.filename)"
      oc scale --replicas=1 dc/$(inputs.params.tenant)-jenkins -n $(inputs.params.project)
      while [[ $(oc get dc $(inputs.params.tenant)-jenkins -n "$(inputs.params.project)" -o 'jsonpath={..status.readyReplicas}') != "1" ]]; do echo "waiting for pod to be ready" && sleep 1; done
      echo "DeploymentConfig $(inputs.params.tenant)-jenkins is scaled to 1 on project $(inputs.params.project)" in cluster: $(inputs.params.cluster)
  workspaces:
  - name: input
    readOnly: true
