apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-rsync
spec:
  params:
  - description: kubeconfig file name
    name: filename
    type: string
  - description: project name
    name: project
    type: string
  - description: tenant name
    name: tenant
    type: string
  - description: name of the cluster
    name: dest_cluster
    type: string
  - description: name of the cluster
    name: source_cluster
    type: string
  - description: username for basic authentication to the cluster
    name: username
    type: string
  - name: pvc
    type: string
  - name: dest_project
    type: string
  results:
  - description: sync results
    name: sync-result
  steps:
    - image: 'quay.io/openshift/origin-cli:4.20'
      name: start-rsync-pod
      resources: {}
      script: >
        #!/usr/bin/env bash

        set -euo pipefail

        trap 's=$?; echo >&2 "$0: Error on line "$LINENO": $BASH_COMMAND"; exit
        $s' ERR

        export
        KUBECONFIG="$(workspaces.input.path)/$(inputs.params.source_cluster)/$(inputs.params.filename)"

        PVC_NAME=$(echo "$(inputs.params.pvc)" | tr '\n' ' ' | xargs)

        oc delete pod $(inputs.params.tenant)-jenkins-rsync -n
        $(inputs.params.project) --ignore-not-found=true

        oc process -f /var/rsync-template/rsync.yaml
        INSTANCE=$(inputs.params.tenant) PROJECT=$(inputs.params.project)
        DEST_PROJECT=$(inputs.params.dest_project)
        DEST_POD="$(inputs.params.tenant)-rsync-reciever" SOURCE_PVC="$PVC_NAME"
        | oc create -f - -n $(inputs.params.project)



        check_counter_max=300
        check_counter=0
        sleep_timer_sec=2


        while [[ $(oc get pods $(inputs.params.tenant)-jenkins-rsync -n
        "$(inputs.params.project)" -o
        'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True"
        && $(oc get pods $(inputs.params.tenant)-jenkins-rsync -n
        "$(inputs.params.project)" -o 'jsonpath={..status.phase}') !=
        "Succeeded" ]]; do 

          echo "waiting for rsync pod to be ready ${check_counter}/${check_counter_max}" && sleep ${sleep_timer_sec} 
          check_counter=$((check_counter+1))
          if [ ${check_counter} == ${check_counter_max} ]; then
            echo "Timed out waiting for rsync pod"
            exit 1
          fi

        done

        echo "rsync pod started successfully"
      volumeMounts:
        - mountPath: /var/rsync-template
          name: rsync-template
    - image: 'quay.io/openshift/origin-cli:4.20'
      name: monitor-rsync
      resources: {}
      script: >
        #!/usr/bin/env bash  

        set -euo pipefail  

        trap 's=$?; echo >&2 "$0: Error on line "$LINENO": $BASH_COMMAND"; exit	$s' ERR  

        export KUBECONFIG="$(workspaces.input.path)/$(inputs.params.source_cluster)/$(inputs.params.filename)"  

        echo -e "Checking rsync status...\nThis step might take time, especially if some data was migrated before on another sync"

        echo -e "\nPlease wait patiently"

        sleep 10

        containerStatus=$(oc get pods -n $(inputs.params.project) $(inputs.params.tenant)-jenkins-rsync -o 'jsonpath={.status.containerStatuses[?(@.name=="rsync")].state.terminated.reason}')

        if [[ ${containerStatus} == "Completed" ]]; then  
          echo "Data migration completed very fast, either the data was already migrated or isn't much to migrate"  
          exit 0
        fi 

        pvc_info=$(oc exec "$(inputs.params.tenant)-jenkins-rsync" -n	
        "$(inputs.params.project)" -- df -h --output=used /var/lib/jenkins | awk	
        'FNR == 2 {print}' 2>/dev/null || echo "No Data") 

        oc logs -f $(inputs.params.tenant)-jenkins-rsync -n	
        $(inputs.params.project) &
        
        src_files="$(oc rsh -n "$(inputs.params.project)" "$(inputs.params.tenant)-jenkins-rsync" bash -c 'find /var/lib/jenkins/jobs/ | wc -l')"
        
        while [ "$(oc get pods $(inputs.params.tenant)-jenkins-rsync -n "$(inputs.params.project)" -o jsonpath='{.status.phase}')" = "Running" ]; do  

          current_size=$(oc exec --kubeconfig='$(workspaces.input.path)/$(inputs.params.dest_cluster)/$(inputs.params.filename)' "$(inputs.params.tenant)-rsync-reciever" -n "$(inputs.params.dest_project)" -- df -h --output=used /var/lib/jenkins | awk 'FNR == 2 {print}')  

          echo "[$(date "+%H:%M:%S")] Migrated $current_size /$pvc_info"  

          sleep 10
        done  

        echo -e "\n[Finished] migration finished, comparing file count on source and destination PVCs..."

        sleep 5

        dst_files="$(oc rsh --kubeconfig='$(workspaces.input.path)/$(inputs.params.dest_cluster)/$(inputs.params.filename)' -n "$(inputs.params.dest_project)" "$(inputs.params.tenant)-rsync-reciever" bash -c 'find /var/lib/jenkins/jobs/ | wc -l')"
        
        if [ "$dst_files" = "$src_files" ]; then
        
          echo "Transferred ${dst_files}/${src_files} files"
        
        else
        
          echo "[FAILED] Transferred ${dst_files}/${src_files} files"
        
          exit 1
        
        fi
    - image: 'quay.io/openshift/origin-cli:4.20'
      name: record-results
      resources: {}
      script: >
        #!/usr/bin/env bash

        set -euo pipefail

        trap 's=$?; echo >&2 "$0: Error on line "$LINENO": $BASH_COMMAND"; exit
        $s' ERR

        export
        KUBECONFIG="$(workspaces.input.path)/$(inputs.params.source_cluster)/$(inputs.params.filename)"

        oc get pods -n $(inputs.params.project)
        $(inputs.params.tenant)-jenkins-rsync | tee $(results.sync-result.path)
  volumes:
    - configMap:
        name: rsync-template
      name: rsync-template
  workspaces:
    - name: input
      readOnly: true
