apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-kubeconfig
spec:
  description: |2-

    Modified by Ido Faigenboim to use secret for token

    This Task do a similar job to the Cluster PipelineResource and are intended as its replacement.
    This task creates a kubeconfig file that can be used to configure access to the different clusters. A common use case for this task is to deploy your application/function on different clusters. The task will use the kubeconfigwriter image and the provided parameters to create a kubeconfig file that can be used by other tasks in the pipeline to access the target cluster.
  params:
  - description: name of the destination cluster
    name: cluster
    type: string
  - description: API address of the destination cluster
    name: url
    type: string
  - description: default namespace to use on unspecified requests
    name: namespace
    type: string
  - description: username for basic authentication to the cluster
    name: username
    type: string
  - description: kubeconfig file name
    name: filename
    type: string
  - default: ""
    description: password for basic authentication to the cluster
    name: password
    type: string
  - default: ""
    description: contains PEM-encoded certificate authority certificates
    name: cadata
    type: string
  - default: ""
    description: contains PEM-encoded data from a client key file for TLS
    name: clientKeyData
    type: string
  - default: ""
    description: contains PEM-encoded data from a client cert file for TLS
    name: clientCertificateData
    type: string
  - default: "false"
    description: to indicate server should be accessed without verifying the TLS certificate
    name: insecure
    type: string
  steps:
  - args:
    - -clusterConfig
    - '{ "name":"$(params.cluster)", "url":"$(params.url)", "username":"$(params.username)",
      "password":"$(params.password)", "cadata":"$(params.cadata)", "clientKeyData":"$(params.clientKeyData)",
      "clientCertificateData":"$(params.clientCertificateData)", "namespace":"$(params.namespace)",
      "token":"$(sa_token)", "Insecure":$(params.insecure) }'
    - -destinationDir
    - $(workspaces.output.path)/$(params.cluster)
    command:
    - /ko-app/kubeconfigwriter
    env:
    - name: sa_token
      valueFrom:
        secretKeyRef:
          key: $(inputs.params.cluster)
          name: jenkins-csb-serviceaccounts
    image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/kubeconfigwriter@sha256:b2c6d0962cda88fb3095128b6202da9b0e6c9c0df3ef6cf7863505ffd25072fd
    name: generate-kubeconfig
    resources: {}
  - image: quay.io/openshift/origin-cli:4.20
    name: test-kubeconfig
    resources: {}
    script: |
      set -euo pipefail
      trap 's=$?; echo >&2 "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
      export KUBECONFIG="$(workspaces.output.path)/$(params.cluster)/$(inputs.params.filename)"
      #
      # check that the cluster is configured
      oc project
      oc whoami
  workspaces:
  - name: output
