apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gather-info
spec:
  params:
  - description: kubeconfig file name
    name: filename
    type: string
  - description: project name
    name: project
    type: string
  - description: tenant name
    name: tenant
    type: string
  - description: name of the cluster
    name: dest_cluster
    type: string
  - description: username for basic authentication to the cluster
    name: username
    type: string
  - name: source_cluster
    type: string
  results:
  - description: The pvc name that will be used in the rsync
    name: pvc-name
  steps:
  - image: quay.io/openshift/origin-cli:4.20
    name: get-pvc
    resources: {}
    script: "#!/usr/bin/env bash\nset -euo pipefail\ntrap 's=$?; echo >&2 \"$0: Error
      on line \"$LINENO\": $BASH_COMMAND\"; exit $s' ERR\nexport KUBECONFIG=\"$(workspaces.input.path)/$(inputs.params.source_cluster)/$(inputs.params.filename)\"\nSOURCE_PVC=$(oc
      get dc $(inputs.params.tenant)-jenkins -n $(inputs.params.project) -o 'jsonpath={..spec.template.spec.volumes[?(@.name==\"jenkins-data\")].persistentVolumeClaim.claimName}')
      \  \necho ${SOURCE_PVC} | tee $(results.pvc-name.path)\n"
  workspaces:
  - name: input
    readOnly: true
