apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/jenkins-csb-deploy
patches:
  - target:
      group: tekton.dev
      version: v1beta1
      kind: Pipeline
      name: jenkins-csb-deploy
    path: patches/jpatch.controller-argo-branch.yaml
