# Minimal Konflux / Pipelines-as-Code: build on pull request (short-lived image tag).
# Replace: metadata.namespace, output-image registry path, build.appstudio.openshift.io/repo.
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/changeme-org/changeme-repo?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main"
      && ( "components/coffee-break/***".pathChanged() || ".tekton/coffee-break-pull-request.yaml".pathChanged() )
  labels:
    appstudio.openshift.io/application: coffee-break
    appstudio.openshift.io/component: coffee-break
    pipelines.appstudio.openshift.io/type: build
  name: coffee-break-on-pull-request
  namespace: changeme-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/changeme-tenant/coffee-break:on-pr-{{revision}}
    - name: dockerfile
      value: Dockerfile
    - name: path-context
      value: components/coffee-break
    - name: image-expires-after
      value: 5d
    - name: skip-checks
      value: "false"
    - name: hermetic
      value: "false"
    - name: prefetch-input
      value: ""
    - name: build-source-image
      value: "false"
    - name: build-image-index
      value: "false"
  pipelineRef:
    params:
      - name: bundle
        value: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build-oci-ta@sha256:f447630920c09c62cc11446c7ce03a6e007f4936f7169e79d2383bb09d46f47b
      - name: name
        value: docker-build-oci-ta
      - name: kind
        value: pipeline
    resolver: bundles
  taskRunTemplate:
    serviceAccountName: build-pipeline-coffee-break
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
