apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: gitlab-monitor-pipeline-template
spec:
  params:
    - name: gitrevision
    - name: sender
      default: "gitlab-monitor@redhat.com"
    - name: recipients
      default: "devops@redhat.com"
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: gitlab-monitor-pipeline-run-
      spec:
        pipelineRef:
          name: gitlab-monitor-pipeline
        podTemplate:
          securityContext:
            fsGroup: 0
            runAsUser: 0
        workspaces:
        - name: output
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              volumeMode: Filesystem
              storageClassName: dynamic-nfs
              resources:
                requests:
                  storage: 1Gi
        params:
        - name: gitrevision
          value: $(tt.params.gitrevision)
        - name: sender
          value: $(tt.params.sender)
        - name: recipients
          value: $(tt.params.recipients) 